# Generated by Django 5.1.7 on 2025-03-20 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Selector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('avito', 'Avito'), ('youla', 'Youla'), ('24au', '24au')], max_length=20, unique=True)),
                ('search_box', models.CharField(max_length=255)),
                ('search_button', models.CharField(max_length=255)),
                ('next_button', models.CharField(max_length=255)),
                ('item', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('price', models.CharField(max_length=255)),
                ('link', models.CharField(max_length=255)),
            ],
        ),
    ]
